# Default values for Helm-based deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applicationDomain: c03.k8s-popup.csc.fi
clusterType: openshift  # either 'kubernetes' or 'openshift'
tlsSecret: mytls-secret

authorization_required: False

storage:
    permanent_dir: '/data/output'
    tmp_dir: '/data/tmp'
    remote_storage_url: 'ftp://ftp-private.ebi.ac.uk/upload/foivos'

autocert:
  createJob: "true"  # actually create autocert cronjob
  schedule: "0 0 1 */2 *"  # cronjob schedule
  testCert: "true"  # use test certificates so as not to exceed quota
  image: elixircloud/autocert:devel
  apiServer: kubernetes.default.svc:443  # address of k8s API server
  email: cert.author@cert.author.host.org  # email to inject into certificate

flower:
  appName: flower
  basicAuth: admin:admin
  image: endocode/flower

wes:
  appName: cwlwes
  image: elixircloud/cwl-wes:latest
  netrcMachine: defaultmachine
  netrcLogin: defaultnetrclogin
  netrcPassword: defaultnetrcpassword
  volumeSize: 1Gi

service_info:
  contact_info: 'https://github.com/elixir-cloud-aai/cwl-WES'
  auth_instructions_url: 'https://www.elixir-europe.org/services/compute/aai'
  tags:
    known_tes_endpoints: 'https://tes.tsi.ebi.ac.uk/|https://tes-dev.tsi.ebi.ac.uk/|https://csc-tesk.c03.k8s-popup.csc.fi/|https://tesk.c01.k8s-popup.csc.fi/|https://csc-tesk-noauth.c03.k8s-popup.csc.fi/'

tes:
  url: 'https://csc-tesk-noauth.c03.k8s-popup.csc.fi/'

celeryWorker:
  appName: celery-worker
  image: elixircloud/cwl-wes:latest

mongodb:
  appName: mongodb
  databaseAdminPassword: adminpasswd
  databaseName: cwlwes-db
  databasePassword: cwlwes-db-passwd
  databaseUser: cwlwes-user
  volumeSize: 1Gi
  image: centos/mongodb-36-centos7

rabbitmq:
  appName: rabbitmq
  volumeSize: 1Gi
  image: rabbitmq:3-management

